### ISSUE TITLE
Where is switch-remote-play-host.exe?

### ISSUE THREAD

**Issue by misch27** [Moehammered/switch-remote-play#10]
"Make sure the ffmpeg.exe program is located in the same folder as the switch-remote-play-host.exe"
So, where is witch-remote-play-host.exe file?

**Comment by Moehammered** [comment]
Hi Mike,

It should be in the same folder as the ffmpeg.exe program. If you cannot see it then your anti virus or Windows defender might have deleted the program. 

Please see https://github.com/Moehammered/switch-remote-play/blob/master/instructions/Instructions.md#virus-threat-detected on how to get the file out of quarantine in windows defender.

**Comment by Moehammered** [comment]
Oh and just in case if you didn't know where to download the release: https://github.com/Moehammered/switch-remote-play/releases/tag/v0.8.1

Please follow the usage instructions.

Enjoy!
