### ISSUE TITLE
Domain name? not IP address

### ISSUE THREAD

**Issue by uepapx** [Moehammered/switch-remote-play#11]

**Comment by Moehammered** [comment]
I'm sorry I don't understand your issue. Could you please explain the issue you're experiencing?

**Comment by uepapx** [comment]
In NiN switch Remote play app, enter not IP adress, domain name of router, and play anywhere. Sorry about my english

**Comment by Moehammered** [comment]
Sorry the switch remote play app only supports LAN networks right now. There is no plan to allow remote play via the internet.

**Comment by uepapx** [comment]
LAN play work good. But internet play as Xbox on mobile phone work perfectly, any ideas about it?

**Comment by Moehammered** [comment]
No idea, sorry. Switch remote play is LAN only.
