### ISSUE TITLE
Controls dropping - creating issue by request

### ISSUE THREAD

**Issue by Ritaku02** [Moehammered/switch-remote-play#13]
So far the controls have only dropped once, but then most of my time with the app has been spent adjusting network settings, then opening the app and running around in Persona 4 Golden to see if the audio's still popping. Here's the network diagnostic from the windows app;

---- Network ----
Looking for active network interfaces...

Found an active network connection.

Ethernet {6FACE69C-06D3-4376-8F2A-61AB250B715B}
    Intel(R) I211 Gigabit Network Connection
    Connection type:                Ethernet interface adapter
    Status:                         Active
    Max Transmission Speed:         1000 megabits/sec | 119.209 megabytes/sec
    Max Receive Speed:              1000 megabits/sec | 119.209 megabytes/sec

    IP Address:  192.168.50.86
    Gateway:     192.168.50.1
    Subnet Mask: 255.255.255.0
    Broadcast:   192.168.50.255

Please make sure your Switch is on the same network as this network connection

Broadcast address for network discovery is: 192.168.50.255

----------------------------------------------------------

My Switch is connected to this same router through 5GHz Wifi. I also tested the 2,4GHz signal with the same results.

Edit: Oh, also, the time the controls cut out, the sound also cut out for the same amount of time. I forget how long the cutout lasted.

**Comment by Moehammered** [comment]
Could you also attach your switch's configuration file? Or copy the text from it and comment it here so I can try and find a pattern if more people report controls dropping out.

Also I'm assuming you're running the latest version of switch remote play(v0.8.3 for both the pc and switch app).

The controls and sound dropping out at the same time is very strange. Does the video continue to stream with no obvious latency when this happens?

Thanks for diagnostic info.

**Comment by Ritaku02** [comment]
Yes, running 0.8.3 of switch remote play. Also, yes, when this happened, the video continued to play just fine, only the sound and controls dropped. Here's the text of the Switch app's config file;

use_manual_mode=no;
broadcast_address=192.168.50.255;
manual_ip=192.168.50.86;
desired_framerate=60;
desktop_resolution=2560x1440;
switch_resolution=1280x720;
bitrate_kb=8192;
vsync_mode=variable frame rate;
encoder_preset=ultrafast;
quality_control_factor=16;
video_codec=h264;
hwaccel_mode=auto;
controller_mode=x360;
controller_map=invert ab;
mouse_left_click=L;
mouse_right_click=R;
mouse_on_connect=no;
mouse_sensitivity=10;
decoder_flags1=low delay;
decoder_flags2=fast;
decoder_hwaccelflags=ignore level;
decoder_skip_loop_filter=discard all;
decoder_thread_type=thread slice;
decoder_thread_count=4;

**Comment by Moehammered** [comment]
Hello there. Could you try using the latest version of the application to see if this issue still occurs?

Latest Full Release: https://github.com/Moehammered/switch-remote-play/releases/tag/0.9.0

Audio Patch for PC Application: https://github.com/Moehammered/switch-remote-play/releases/tag/0.9.0-pc-audio-patch

Thanks.

**Comment by Moehammered** [comment]
closed due to going stale.
