### ISSUE TITLE
Don't work :(

### ISSUE THREAD

**Issue by virienko** [Moehammered/switch-remote-play#14]
After connection and pressing R i see PC display on my Switch for only 1 sec. Then it back to main menu...

I have an error in console : Failed to connect bus for virtual controller with error code: 0xe0000001

**Comment by Moehammered** [comment]
Hi there.

The program is saying the virtual controller is not connecting. Did you install the virtual controller driver?

Please see this issue: https://github.com/Moehammered/switch-remote-play/issues/4
