### ISSUE TITLE
There is no switch-remote-play-host.exe like it shows in the instructions

### ISSUE THREAD

**Issue by CommicKick69ing** [Moehammered/switch-remote-play#15]
There is switch-remote-play-host.exe like it says in the instructions so I not sure how Im expected to use this program. Where can I download switch-remote-play-host.exe?

**Comment by Moehammered** [comment]
Hi there. 

You're antivirus is deleting or quarantining the program. If you downloaded the zip file from the release then it also might have deleted the program from the zip file. 

Please download the 7z archive, extract it, then check the instructions on "virus detected".
