### ISSUE TITLE
If this doesn't work, or stays stuck on 'Searching'and all the steps have been followed

### ISSUE THREAD

**Issue by CommicKick69ing** [Moehammered/switch-remote-play#16]
If this doesn't work, or stays stuck on 'Searching'. I got a windows firewall prompt and made sure to ALLOW the program access and made sure Flight Mode is OFF and your Switch and PC are connected on the same network. What's going on?

**Comment by Moehammered** [comment]
If it says stuck searching then you did not set-up the broadcast address for your switch. The PC program on startup outputs a broadcast address amd instructs you to copy it to the config file for the switch.

If you do not get the broadcast address or don't know what to do, use manual IP mode. Please read the instructions.
