### ISSUE TITLE
Stuck on Stream pending Connection...

### ISSUE THREAD

**Issue by lebertovic** [Moehammered/switch-remote-play#23]
Hey, i cant start a stream, the homebrew stucks right after i press R when it says Stream pending Connection... What should i do?

**Comment by Moehammered** [comment]
Hi there.

Did you follow the instructions for how to connect? https://github.com/Moehammered/switch-remote-play/blob/master/instructions/Instructions.md

Have you tried manual IP mode?

If you're still having trouble after reading the instructions please show me the -----Network----- output from the PC application when you start it up.

**Comment by lebertovic** [comment]
hey, thanks for your fast response. Yes ive done it like its ´says in the instruction. And manual ip doesnt work neither

here is my network output:

---- Network ----
Looking for active network interfaces...

Found an active network connection.

    Realtek Gaming GbE Family Controller
    Connection type:                Ethernet interface adapter
    Status:                         Active
    Max Transmission Speed:         1000 megabits/sec | 119.209 megabytes/sec
    Max Receive Speed:              1000 megabits/sec | 119.209 megabytes/sec

    IP Address:  192.168.178.62
    Gateway:     192.168.178.1
    Subnet Mask: 255.255.255.0
    Broadcast:   192.168.178.255

Please make sure your Switch is on the same network as this network connection

Broadcast address for network discovery is: 192.168.178.255

**Comment by lebertovic** [comment]
is it maybe because of the gateway? how do i write that in to the config file?

**Comment by Moehammered** [comment]
Thanks for the output.

Have you tried connecting the app via manual ip mode using your computer's IP address? (192.168.178.62)

You cannot change the gateway but you can change the broadcast address in the config file for the switch application. In the switch remote play folder on your switch SD card there will be a config file. You can add the broadcast address there.

Could you please supply the config file for the switch app on your SD card?

And finally, are your switch and PC connected to the same  network?

Hope that helps.

**Comment by lebertovic** [comment]
hey, sorry for the late answer. yes ive tried manual ip mode and yes the devices are in the same network.

this is the config file:

use_manual_mode=yes; ( both yes and no doesnt work)
broadcast_address=192.168.178.255;
manual_ip=192.168.178.62;
desired_framerate=60;
desktop_resolution=1280x720;
switch_resolution=1280x720;
bitrate_kb=8192;
vsync_mode=variable frame rate;
encoder_preset=ultrafast;
quality_control_factor=16;
video_codec=h264;
hwaccel_mode=auto;
controller_mode=x360;
controller_map=default;
mouse_left_click=L;
mouse_right_click=R;
mouse_on_connect=no;
mouse_sensitivity=10;
decoder_flags1=;
decoder_flags2=fast;
decoder_hwaccelflags=ignore level;
decoder_skip_loop_filter=discard all;
decoder_thread_type=thread slice;
decoder_thread_count=4;

**Comment by Moehammered** [comment]
If you try and use the automatic network discovery, does it work?
Disable manual ip mode. Then press the L button on the switch.

If it stays stuck searching then there's 2 possibilities:
The switch is not on the same network.
The pc firewall is blocking the connection.

Can you confirm for me that windows firewall is not blocking the application?

When you try to use network discovery or attempt to connect, does the pc application display any errors?

Lastly, is ffmpeg.exe located in the same folder as switch-remote-play-host on your pc? Is ffmpeg blocked by your firewall?

**Comment by lebertovic** [comment]
Yes automatic discovery works, on my switch i get the green ip address when i press L and on my computer the host programm says :

waiting for connection...

Connecting to: 192.168.178.73
Sent reply to switch: let-me-play

yes i unblocked both applications (the host app and ffmpeg) but im using McAfee Antivirus and not the normal windows defender, i dont know maybe its a little bit different with McAfee?

**Comment by Moehammered** [comment]
Maybe the McAfee antivirus is interfering? I can't be certain as I only use the built in windows defender.

When you attempt to connect, can you show me what the pc program displays?
In the config file for the PC program there is an option to display diagnostic data. Could you enable the option to display ffmpeg output?
The only thing I can think of is ffmpeg is failing to start.
If a connection fails it will print out things about termination.

Please, if you could, show me the output of the pc program when attempting to connect with the show ffmpeg output option enabled in the PC program config.

Thanks for being patient.

**Comment by Moehammered** [comment]
Closing due to issue going stale and not being reproduce-able with currently released version.
