### ISSUE TITLE
Apparently, I can't use this app...

### ISSUE THREAD

**Issue by joey-lg** [Moehammered/switch-remote-play#26]
Because this error occurred after my moniter breifly turned black, then reappeared and the command prompt gave me this error message.

C:\Users\Joseph Goldsmith\Downloads\switch-remote-play-host\ffmpeg.exe -probesize 32 -hwaccel auto -y -f gdigrab -framerate 60 -vsync vfr -video_size 1280x720 -i desktop -f h264 -vcodec h264 -vf "scale=1280x720" -preset ultrafast -crf 16 -tune zerolatency -pix_fmt yuv420p -x264-params "nal-hrd=vbr:opencl=true" -b:v 8192k -minrate 8192k -maxrate 8192k -bufsize 8192k tcp://10.0.0.110:20003
Failed to start process. CreateProcess error code: 193
Argument line passed to cmd:

C:\Users\Joseph Goldsmith\Downloads\switch-remote-play-host\ffmpeg.exe -probesize 32 -hwaccel auto -y -f gdigrab -framerate 60 -vsync vfr -video_size 1280x720 -i desktop -f h264 -vcodec h264 -vf "scale=1280x720" -preset ultrafast -crf 16 -tune zerolatency -pix_fmt yuv420p -x264-params "nal-hrd=vbr:opencl=true" -b:v 8192k -minrate 8192k -maxrate 8192k -bufsize 8192k tcp://10.0.0.110:20003
Failed to start process. CreateProcess error code: 193
Argument line passed to cmd:

C:\Users\Joseph Goldsmith\Downloads\switch-remote-play-host\ffmpeg.exe -y  -f dshow -i audio="virtual-audio-capturer" -f s16le -ar 48000 -ac 2 -c:a pcm_s16le udp://10.0.0.110:20004
waiting for gamepad thread to shutdown...
making sure to kill stream...
terminating the FFMPEG process
Resetting resolution
Restoring audio mute state
Ready to receive a connection from the switch...

waiting for connection to server...

Any help would be appreciated.
And yes, i did meet all the prerequisites.

**Comment by Moehammered** [comment]
Hi there. Thanks for the console output.

The error code 193 means the file is not an executable according to the CreateProcess windows docs.

Could you please confirm the following:
- switch-remote-play-host.exe and ffmpeg.exe are located in the same directory
- Firewall access is allowed for the 2 executables
- That [Screen Capture Recorder to Video Windows free v0.12.11](https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11) is installed

Thanks.

**Comment by Moehammered** [comment]
I have been able to replicate this issue. It only occurs when attempting to run the `switch-remote-play-host.exe` from a command prompt or from a powershell window. Make sure to run the program by double-clicking it.
