### ISSUE TITLE
unable to find 'switch-remote-play-host.exe'

### ISSUE THREAD

**Issue by AleTheArtist** [Moehammered/switch-remote-play#28]
I was following the guide in the instructions folder but i wasn't not able to find any 'switch-remote-play-host.exe' program in the repository

**Comment by Moehammered** [comment]
Hi there. Did you download one of the archives listed in the release? https://github.com/Moehammered/switch-remote-play/releases/tag/v0.8.3

Either the zip or 7z file.

If you did and you decompressed it and it's still not there, please check windows defender to see if it quarantined the program. If it did remove it from quarantine by allowing it in windows defender. Please refer to the help section at the bottom of the instructions.

Hope that helps.

**Comment by Jayinem** [comment]
It is definitely antivirus it kept trying to delete mine until I made an exception in my antivirus.

**Comment by Moehammered** [comment]
Any one else receiving this issue please see the wiki page for more details.

https://github.com/Moehammered/switch-remote-play/wiki/6.-Windows-Security-(Virus-Threat-Detected)
