### ISSUE TITLE
Audio doesn't stream to switch

### ISSUE THREAD

**Issue by ItzNotAstro** [Moehammered/switch-remote-play#35]
I've tried allowing both ffmpeg and the pc host in the firewall, both app and pc are on the same version, tried the latest audio fix patch. still doesn't work. no matter what I do audio will not stream to the switch

**Comment by yabuki-joe** [comment]
did you install the vigem bus program and the screen capture program listed in the getting started guide in the wiki? i skipped that step initially and got picture but no audio, installing both fixed my audio issue although it still isn't great quality wise.

**Comment by Moehammered** [comment]
@ItzNotAstro as @yabuki-joe suggested, please make sure the programs listed in the getting started section of the wiki are installed. The screen capture program is the one that is used for audio capture. 

Please try reinstalling the screen capture program, then try streaming again.

**Comment by bad1dea** [comment]
there's a bug currently if you do not gracefully turn off the stream (i.e put switch to sleep) then unsleep -> reconnect.. audio will not work.. you have to exit app/homebrew and reload and reconnect and sound works.
