### ISSUE TITLE
Virtual Touch - Resolution Mismatch/Touch

### ISSUE THREAD

**Issue by bad1dea** [Moehammered/switch-remote-play#37]
Hey,

Just compiled the latest commits you did to test out the Virtual Touch..

If you don't want me reporting any testing/bugs let me know but.

Virtual Touch -- and Touch Mouse Input

Desktop Resolution: 1440p
Switch Resolution: 720p

Touch will only do part of the screen (i.e 720p - from origin 0:0) there's no calculation for touch input from switch to desktop resolution.

**Comment by Moehammered** [comment]
Hey mate,

Firstly, thanks heaps for taking the initiative to compile and test it yourself. It's very helpful to get testing feedback before a release! :)

Secondly, the touch related features aren't finished yet. The simulated touch mouse is not integrated entirely, only the virtual touch for now.

That said, thank you for catching out this issue. I have only been testing at 720p this entire time. You've reminded to test at other resolutions.

I'll look at fixing this when I do more work on the touch input features. 

Thanks so much!

**Comment by bad1dea** [comment]
NP... I believe the formula is -- didn't bother trying to make changes to your code since you're actively developing it.

(switchX / switchResX) * desktopResX
(switchY / switchResY) * desktopResY

**Comment by Moehammered** [comment]
@bad1dea Patched up. If you find an issue with the touch co-ordinates being off, feel free to re-open this issue.

Only changes made were to the PC application. Switch app is unaffected.

Thanks for testing out the application. If you find anymore issues with in progress features, feel free to report them. :)

**Comment by bad1dea** [comment]
Tested - working now the way it's intended now.
