### ISSUE TITLE
[Feature Request] Setting arrows keys

### ISSUE THREAD

**Issue by ganonleboucher** [Moehammered/switch-remote-play#38]
Hi mate! I was wondering if it would be possible to implement the use of the arrows of the controller for matching the arrows of the keyboard when in mouse mode as well as the "A" button for matching the "Enter" key?
Cheers

**Comment by Moehammered** [comment]
@ganonleboucher Hey there champ.

Sure thing, I'll get on adding that. I was planning to add some key bindings to the face buttons so I'll make sure to include the arrows and the enter key in there as options.

It'll be in the 'In Progress' column on the kanban board once I start work on it.

Cheers.
