### ISSUE TITLE
bug: Failed to connect bus for virtual controller with error code: 0xe0000001

### ISSUE THREAD

**Issue by sir1st** [Moehammered/switch-remote-play#4]
connection success just one frame(i can see my computer's desktop in switch) then connection breaks.(hold R and it will connect success in another frame and then break)
this is the log information.(run as the administrator)
Switch Remote Play Host \(^.^)/ (PC Application version - 0.8.1)

Ready to receive a connection from the switch...

waiting for connection to server...

Expected size of command payload: 64 bytes
Reading command...
Start stream with last received config from switch...
FFMPEG Configuration:
Vsync Mode: 2 (variable frame rate)
Target Framerate: 60 fps
Video Capture Size(x,y): 1280, 720
Stream Scale Size(x,y): 1280, 720
Target Stream Bitrate: 8192 kb/s

C:\Users\11747\Desktop\switch-remote-play-host\ffmpeg.exe -probesize 32 -hwaccel auto -y -f gdigrab -framerate 60 -vsync vfr -video_size 1280x720 -i desktop -f h264 -vcodec h264 -vf "scale=1280x720" -preset ultrafast -crf 16 -tune zerolatency -pix_fmt yuv420p -x264-params "nal-hrd=vbr:opencl=true" -b:v 8192k -minrate 8192k -maxrate 8192k -bufsize 8192k tcp://192.168.31.181:20003
waiting for connection to server...

ffmpeg version 4.3.1-2020-11-19-essentials_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[gdigrab @ 0000027e4700f340] Capturing whole desktop as 1280x720x32 at (0,0)
waiting for gamepad thread to shutdown...
[gdigrab @ 0000027e4700f340] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, gdigrab, from 'desktop':
  Duration: N/A, start: 1611824595.388240, bitrate: 1769497 kb/s
    Stream #0:0: Video: bmp, bgra, 1280x720, 1769497 kb/s, 60 fps, 1000k tbr, 1000k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (bmp (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0000027e47013a00] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0000027e47013a00] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit
Output #0, h264, to 'tcp://192.168.31.181:20003':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 8192 kb/s, 60 fps, 60 tbn, 60 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 8192000/0/8192000 buffer size: 8192000 vbv_delay: N/A
Failed to connect bus for virtual controller with error code: 0xe0000001
making sure to kill stream...
terminating the FFMPEG process
Resetting resolution
Restoring audio mute state
Ready to receive a connection from the switch...

waiting for connection to server...

**Comment by Moehammered** [comment]
Hey there, thanks for the detailed log. 

Looks like there's an issue with the virtual controller. The stream will always automatically close if the controller disconnects or fails. 

Can you please make sure the required software from the pc install instructions is installed? 
https://github.com/Moehammered/switch-remote-play/blob/master/instructions/Instructions.md#pc-install

If it still fails, can you try uninstalling the ViGEm Bus Driver listed in the install instructions and instead install the latest version of the ViGEm Bus Driver? 

Let me know if that helps.

**Comment by sir1st** [comment]
after uninstall those softwares, reboot and reinstall them, it works. thanks.(maybe something goes wrong when i first install those softwares)
