### ISSUE TITLE
Can't get it to work on 12.1 black screen on switch

### ISSUE THREAD

**Issue by Jayinem** [Moehammered/switch-remote-play#48]
I tried 0.9 and 1.0. I  copied the files to the root of the sd card that includes the switch folder so that it goes to the proper place. I followed all these instructions

1. Download and install 'Screen Capture Recorder to Video Windows free' v0.12.11
    - Link: https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases/tag/v0.12.11

2. Download and install 'ViGEM Bus' v1.16.116
    - Link: https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.16.116

3. Copy the 'switch-remote-play-host' folder from the PC folder to anywhere you like (Downloads, Desktop, Documents, etc...)

4. Make sure to whitelist it in Windows Security as it will be flagged as a virus and be quarantined

It used to work but now just black screen on the Switch. 

Does 1.0 require me to update my switch? I did also do clean install on both PC and Switch but just black screen.

**Comment by Moehammered** [comment]
@Jayinem thank you so much for the detailed breakdown of your troubleshooting. That helps a lot. :)

Can you clarify for me:
- When you say black screen, what do you mean? The stream is black or when you attempt to open the program on your Switch it is a black screen?
- What version of Atmosphere are you using? (I'm assuming your system firmware is 12.1)
- Did it work on an older system firmware and older Atmosphere version?

If it is an update issue, I will try updating my Switch and seeing if I can replicate the issue.
- For reference, I keep my Switch on firmware 10.1 and use Atmosphere 1.2.4 with Hekate

**Comment by Jayinem** [comment]
It turns out it works it just black screens for awhile maybe 30 seconds to a minute then finally comes on I didn't realize it. thanks
