### ISSUE TITLE
Audio is not streamed

### ISSUE THREAD

**Issue by Rotingus** [Moehammered/switch-remote-play#49]
I tried to install screen capture and vigem bus. The audio is still not streamed. I just saw that  2 ffmpeg.exe are opened by switch remote play, I think it might be the problem.

**Comment by Rotingus** [comment]
But, after closing one of the ffmpeg and recharging the switch remote play on the pc and the switch. The sound came back. If I close the task manager, the sound cannot be streamed to the switch.. I'm using the version 1.0.0

**Comment by Moehammered** [comment]
Thanks for the information.
Switch remote play opens 2 ffmpeg.exe processes on purpose. 1 is for video, the other is for audio. So seeing 2 is fine.
If audio doesn't stream correctly, please disconnect the stream. Then open Task Manager and check if there are any open ffmpeg.exe processes open.

When switch remote play disconnects there should be no ffmpeg process open by it.
When switch remote play connects, there should be 2 ffmpeg processes open.
