### ISSUE TITLE
Virtual controller drive 

### ISSUE THREAD

**Issue by MookieMike** [Moehammered/switch-remote-play#58]
!!! Virtual Controller driver seems to be having issues. Please make sure it is installed correctly. !!!
If the problem persists, please try uninstalling the driver and installing the latest virtual controller driver

This is the error message I get when I run it on my computer and the stream is not working. I tried re-installing but that didn't work.

**Comment by Moehammered** [comment]
Hey mate. Have you followed the wiki on how to get setup?
Please try reinstalling the PC related software again and try again.
https://github.com/Moehammered/switch-remote-play/wiki/01.-Getting-Started#pc-installation

If it still doesn't work, can you please provide more information about your PC?
- CPU
- GPU
- Windows version
- Using Wifi or ethernet
- Allowed switch-remote-play-host and ffmpeg through firewall

What version of the virtual controller driver are you attempting to install?

**Comment by Rimkush92** [comment]
Hello there
I'm trying to install your software, but I'm encoutering the same issue as quoted by @MookieMike 
On my side,
Ryzen 3600X 
RTX 3070
Win 10 Family
Tried with Wifi and ethernet (checked ip via ipconfig)
Both apps are allowed via windows firewall (and never got deleted)

I tried so many differents IPs and Broadcast adress but didn't found the solution

network.ini : Audio Port=20004;
Video Port=20003;
Command Port=20001;
Gamepad Port=20002;
Handshake Port=19999;
Broadcast Port=20000;
Broadcast Address=192.168.1.255; (tried 254 with wifi too)
Manual IP Enabled=yes;
Manual IP Adress=192.168.1.89;

**Comment by mufanvn** [comment]
I having same issue.
==========================================

  Client allocation successful.
    Virtual Controller connection failed with error code: 0xe0000001

!!! Virtual Controller driver seems to be having issues. Please make sure it is installed correctly. !!!
If the problem persists, please try uninstalling the driver and installing the latest virtual controller driver


==== Press enter to close the program... ====

**Comment by mufanvn** [comment]
> # I having same issue.
> Client allocation successful. Virtual Controller connection failed with error code: 0xe0000001
> 
> !!! Virtual Controller driver seems to be having issues. Please make sure it is installed correctly. !!! If the problem persists, please try uninstalling the driver and installing the latest virtual controller driver
> 
> ==== Press enter to close the program... ====

after follow #4  and installed [ViGEmBus](https://github.com/ViGEm/ViGEmBus), it's Good.
Should add this to the readme.
Thanks

**Comment by Moehammered** [comment]
Please consult the wiki in the future. The setup for the driver is explained there, along with many other things.
https://github.com/Moehammered/switch-remote-play/wiki

@mufanvn any other issues, I hope the wiki has the answers to help. :)
