### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by VoidNinjaaa** [Moehammered/switch-remote-play#66]
Ive installed it and it works great appart from that i dont get any audio on my switch..

**Comment by benj0670** [comment]
Same here. Had issues with Moonlight-NX so I tried this out. No audio which renders my game unplayable as it is key

**Comment by benj0670** [comment]
Fixed it by installing Screen Capturer Recorer mentioned on the In-Home-Switching repo:

https://github.com/rdp/screen-capture-recorder-to-video-windows-free/releases

**Comment by Moehammered** [comment]
Please consult the wiki in the future:
https://github.com/Moehammered/switch-remote-play/wiki

@Glitch-Codes and @VoidNinjaaa I hope any other issues you have will be answerable in the wiki I've written.
