### ISSUE TITLE
yuv420p - color banding

### ISSUE THREAD

**Issue by BFCE** [Moehammered/switch-remote-play#7]
Any way to get 4:4:4?

**Comment by Moehammered** [comment]
Hey there. It could be possible but I'd have to write something to render that format. And that format will increase the packet size of frames making latency an issue.

Have you tried playing around with the preset, quality control factor, and bitrate settings in the encoder configuration screen?

I don't plan to support other yuv formats as it's not worth the time compared to other features at this point in time.
